// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKHPl4bCR3Q7cpkTAPJMmn0oDD4PiuBKc',
    appId: '1:239573396548:web:c975e53741436f3e41a011',
    messagingSenderId: '239573396548',
    projectId: 'quiz-app-701a3',
    authDomain: 'quiz-app-701a3.firebaseapp.com',
    storageBucket: 'quiz-app-701a3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwkl9AxF8_4ufJniJSomT15RitXbeT7dU',
    appId: '1:239573396548:android:76d49e81cced415c41a011',
    messagingSenderId: '239573396548',
    projectId: 'quiz-app-701a3',
    storageBucket: 'quiz-app-701a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxZdEvEVJPrMSDAGGYduKrIv7kE48cZsQ',
    appId: '1:239573396548:ios:f309fa79714058b241a011',
    messagingSenderId: '239573396548',
    projectId: 'quiz-app-701a3',
    storageBucket: 'quiz-app-701a3.appspot.com',
    iosClientId: '239573396548-tgn9vkqf6t9aieg2tipsqna1lc3b0fnq.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxZdEvEVJPrMSDAGGYduKrIv7kE48cZsQ',
    appId: '1:239573396548:ios:658ae43808dd377b41a011',
    messagingSenderId: '239573396548',
    projectId: 'quiz-app-701a3',
    storageBucket: 'quiz-app-701a3.appspot.com',
    iosClientId: '239573396548-dq96pg0kq12pmu6qevqf73pkcq6hrmce.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp.RunnerTests',
  );
}
